name: pro_pretty_logging
description: The library provides a grade solution for enhancing logging in your Dart applications.
version: 1.0.5

repository: https://github.com/pro100andrey/pro_pretty_logging
issue_tracker: https://github.com/pro100andrey/pro_pretty_logging/issues
homepage: https://github.com/pro100andrey/pro_pretty_logging
documentation: https://github.com/pro100andrey/pro_pretty_logging/blob/main/README.md

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: "^3.0.0"

dependencies:
  logging: ^1.2.0

dev_dependencies:
  pro_lints: ^2.0.2
